---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/component: {{ .Chart.Name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  revisionHistoryLimit: {{ .Values.deployment.revisionHistoryLimit }}
  replicas: {{ .Values.deployment.replicas }}
  strategy:
    type: "{{ .Values.deployment.strategyType }}"
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}
    spec:
      containers:
        - name: "{{ .Chart.Name }}"
          image: "{{ .Values.deployment.image }}"
          imagePullPolicy: "{{ .Values.global.imagePullPolicy }}"
          resources:
            requests:
              memory: "{{ .Values.deployment.requestMemory }}"
              cpu: "{{ .Values.deployment.requestCpu }}"
            limits:
              memory: "{{ .Values.deployment.limitMemory }}"
              cpu: "{{ .Values.deployment.limitCpu }}"
          ports:
            - name: {{ .Chart.Name }}
              containerPort: {{ .Values.deployment.containerPort }}
          volumeMounts:
          - name: {{ .Release.Name }}-{{ .Chart.Name }}-conf
            mountPath: /etc/nginx/{{ .Values.nginxConf }}
            subPath: {{ .Values.nginxConf }}
            readOnly: true
      volumes:
        - name: {{ .Release.Name }}-{{ .Chart.Name }}-conf
          configMap:
            name: {{ .Release.Name }}-{{ .Chart.Name }}-conf
            items:
              - key: {{ .Values.nginxConf }}
                path: {{ .Values.nginxConf }}
