name: Sausage Store Deploy

on:
  push:
    branches:
      - main

env:
  NEXUS_HELM_REPO: ${{ secrets.NEXUS_HELM_REPO }}
  NEXUS_HELM_REPO_USER: ${{ secrets.NEXUS_HELM_REPO_USER }}
  NEXUS_HELM_REPO_PASSWORD: ${{ secrets.NEXUS_HELM_REPO_PASSWORD }}
  SAUSAGE_STORE_NAMESPACE: ${{ secrets.SAUSAGE_STORE_NAMESPACE }}
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
  VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
  DOCKERHUB: ${{ secrets.DOCKERHUB }}
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build_and_push_to_docker_hub:
      name: Push Docker image to DockerHub
      runs-on: ubuntu-latest
      steps:
        - name: Check out the repo
          uses: actions/checkout@v3
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Login to Docker
          uses: docker/login-action@v2
          with:
            username: ${{ env.DOCKER_USER }}
            password: ${{ env.DOCKER_PASSWORD }}

        - name: Push Backend to DockerHub
          uses: docker/build-push-action@v4
          with:
            context: ./backend/
            push: true
            tags: ${{ env.DOCKERHUB }}/sausage-backend:latest
            build-args: |
              VERSION=${{ github.sha }}

        - name: Push Frontend to DockerHub
          uses: docker/build-push-action@v4
          with:
            context: ./frontend/
            push: true
            tags: ${{ env.DOCKERHUB }}/sausage-frontend:latest

        - name: Push Backend-report to DockerHub
          uses: docker/build-push-action@v4
          with:
            context: ./backend-report/
            push: true
            tags: ${{ env.DOCKERHUB }}/sausage-backend-report:latest


#  add_helm_chart_to_nexus:
#      name: Add Helm Chart To Nexus
#      runs-on: ubuntu-latest
#      needs: build_and_push_to_docker_hub
#
#      steps:
#      #### Опишите необходимые шаги
#
#  deploy_helm_chart_to_kubernetes:
#      name: Deploy Helm Chart To Kubernetes
#      runs-on: ubuntu-latest
#      needs: add_helm_chart_to_nexus
#
#      steps:
#      #### Опишите необходимые шаги